export const ideaSchema = {
  type: "object",
  properties: {
    id: { type: "string", nullable: false },
    schoolId: { type: "string" },
    teacherId: { type: "string" },
    solutionName: { type: "string" },
    solutionType: { type: "string" },
    probleamArea: { type: "string" },
    probleamSelection: { type: "string" },
    probleamReasoning: { type: "string" },
    solutionVision: { type: "string" },
    solutionMission: { type: "string" },
    solutionBenefit: { type: "string" },
    solutionObstacle: { type: "string" },
    solutionPitchUrl: { type: "string" },
    targetOutcomes: { type: "string" },
    targetCustomer: { type: "string" },
    potentialCollaboration: { type: "string" },
    solutionSupportingPhotos: { type: "array" },
    isDraft: { type: "boolean" },
  },
};

export const ideaInputSchema = {
  type: "object",
  // required: ["name", "img"],
  properties: {
    schoolId: { type: "string" },
    teacherId: { type: "string" },
    solutionName: { type: "string" },
    solutionType: { type: "string" },
    probleamArea: { type: "string" },
    probleamSelection: { type: "string" },
    probleamReasoning: { type: "string" },
    solutionVision: { type: "string" },
    solutionMission: { type: "string" },
    solutionBenefit: { type: "string" },
    solutionObstacle: { type: "string" },
    solutionPitchUrl: { type: "string" },
    targetOutcomes: { type: "string" },
    targetCustomer: { type: "string" },
    potentialCollaboration: { type: "string" },
    solutionSupportingPhotos: { type: "array" },
    isDraft: { type: "boolean" },
  },
};
